#define comentarioP 1
#define ComentarioSQL 2
#define comparacion 3
#define suma 4
#define resta 5
#define impresionc 6
#define impresionp 7
#define negacionc 8
#define texto 9
#define powerP 10
#define comentarioC 11
#define orC 12
#define negacionp 13
#define suma1 14
#define varsum1 15
#define compar 16
#define andp 17