a = ['alfa','altura','alien']
b = 'bandida'
c = 'coqueta'
d = 'dinamita'
e = ['expensiva','emperatriz','enimga enterada']
f = 'flux æon'
g = 'guapa'
h = 'hondura'
i = 'inteligencia artificial'
j = 'jineta'
m = ['motomami','motomami motmomami', 'motomami motomami']
n = 'ni se te ocurra ni pensarlo'
o = 'orquidea'
p = 'patrona'
q = 'qué reinona'
r = ['racineta','racineta rango','racineta rango']
s = 'sata'
t = 'titánica'
u = 'ultrasonido'
v = 'vendéta'
w = ['willy colón','winterfall']
x = 'te despejo la equis en un momento'
y = ['yenes','yanta']
z = ['zarzamora','zapateao','zorra']